services:
  app:
    image: pokemon/api
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
    ports:
      - '8080:8080'
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
